include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  errors:
    todo: ignore
  exclude:
#    - 'test/**_expected*'
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    dangling_library_doc_comments: true
    directives_ordering: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    use_super_parameters: true